os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git ../flutter -b beta --depth 1
  - ../flutter/bin/flutter doctor
jobs:
  include:
    - stage: Test
      language: generic
      script:
        - $(find lib -type f | grep "[A-Z]") # file names are not allowed to include capital letters
        - $(../flutter/bin/cache/dart-sdk/bin/dartfmt -n lib) # check if files are formatted according to dartfmt
        - ../flutter/bin/flutter analyze
        - ../flutter/bin/flutter test
    - stage: Deploy
      if: branch = master
      language: android
      android:
        components:
          # The BuildTools version used by your project
          - build-tools-28.0.2
          # The SDK version used to compile your project
          - android-27
          # Sys image for eventual virtual devices
          - sys-img-armeabi-v7a-android-26
      script: ../flutter/bin/flutter -v build apk
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Releases"
  - git config --local user.email "releases@cie-app.de"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
   provider: releases
   api_key: $GithubToken
   file: "build/app/outputs/apk/release/app-release.apk"
   skip_cleanup: true
cache:
  directories:
  - $HOME/.pub-cache
